#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Enerdroid_ver_0_1_5.py

Functions
---------
1. Convert mode
   - Convert Gaussian optimization .out files to single-point .gjf files
   - Auto-read final charge and multiplicity
   - Auto-write %chk
   - Remember last route line
   - Skip existing target .gjf files

2. Check mode
   - Submode 1: check whether .out files terminated normally
   - Submode 2: check whether any .gjf has no matching .out

3. Statistics mode
   - Pair xx.out with xx_SP.out
   - Only include pairs where both files completed successfully
   - Build/update Excel summary
   - Preserve manual edits as much as possible:
       * preserve extra columns
       * preserve row formatting / widths / heights
       * preserve structure column content
   - Support canonical header aliases
   - Sort by family similarity + energy proximity

4. Exit slogan
   - Fixed exit line is always shown
   - Custom exit line is shown below it if present
   - Enter new line to replace it
   - Enter 'clear' to remove it
"""

from __future__ import annotations

import copy
import json
import re
import time
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any

from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


# ============================================================================
# Constants
# ============================================================================

VERSION = "Enerdroid_ver_0_1_5.py"
CONFIG_FILE_NAME = "enerdroid_config.json"
FIXED_EXIT_SLOGAN = "程序结束 / Program exited."

ELEMENTS = {
    1: "H",   2: "He",
    3: "Li",  4: "Be",  5: "B",   6: "C",   7: "N",   8: "O",   9: "F",   10: "Ne",
    11: "Na", 12: "Mg", 13: "Al", 14: "Si", 15: "P",  16: "S",  17: "Cl", 18: "Ar",
    19: "K",  20: "Ca", 21: "Sc", 22: "Ti", 23: "V",  24: "Cr", 25: "Mn", 26: "Fe",
    27: "Co", 28: "Ni", 29: "Cu", 30: "Zn", 31: "Ga", 32: "Ge", 33: "As", 34: "Se",
    35: "Br", 36: "Kr", 37: "Rb", 38: "Sr", 39: "Y",  40: "Zr", 41: "Nb", 42: "Mo",
    43: "Tc", 44: "Ru", 45: "Rh", 46: "Pd", 47: "Ag", 48: "Cd", 49: "In", 50: "Sn",
    51: "Sb", 52: "Te", 53: "I",  54: "Xe", 55: "Cs", 56: "Ba", 57: "La", 58: "Ce",
    59: "Pr", 60: "Nd", 61: "Pm", 62: "Sm", 63: "Eu", 64: "Gd", 65: "Tb", 66: "Dy",
    67: "Ho", 68: "Er", 69: "Tm", 70: "Yb", 71: "Lu", 72: "Hf", 73: "Ta", 74: "W",
    75: "Re", 76: "Os", 77: "Ir", 78: "Pt", 79: "Au", 80: "Hg", 81: "Tl", 82: "Pb",
    83: "Bi", 84: "Po", 85: "At", 86: "Rn",
    87: "Fr", 88: "Ra", 89: "Ac", 90: "Th", 91: "Pa", 92: "U",  93: "Np", 94: "Pu",
    95: "Am", 96: "Cm", 97: "Bk", 98: "Cf", 99: "Es", 100: "Fm", 101: "Md", 102: "No",
    103: "Lr", 104: "Rf", 105: "Db", 106: "Sg", 107: "Bh", 108: "Hs", 109: "Mt",
    110: "Ds", 111: "Rg", 112: "Cn", 113: "Nh", 114: "Fl", 115: "Mc", 116: "Lv",
    117: "Ts", 118: "Og",
}

COMMON_ERROR_PATTERNS: list[tuple[str, str]] = [
    (r"\bntrex1\b", "ntrex1"),
    (r"Illegal ITpye or MSType generated by parse", "Illegal ITpye or MSType generated by parse"),
    (r"\bQPErr\b", "QPErr"),
    (r"End of file in ZSymb", "End of file in ZSymb"),
    (r"Found a string as input", "Found a string as input"),
    (r"There are no atoms in this input structure", "There are no atoms in this input structure"),
    (r"Symbol .* not found in Z-matrix", "Symbol not found in Z-matrix"),
    (r"Variable index .* out of range", "Variable index is out of range"),
    (r"Unknown center", "Unknown center / Variable index is out of range"),
    (r"Attempt to redefine unrecognized symbol", "Attempt to redefine unrecognized symbol"),
    (r"RedCar/ORedCr failed for GTrans", "RedCar/ORedCr failed for GTrans"),
    (r"Error imposing constraints", "Error imposing constraints"),
    (r"FormBX had a problem", "FormBX had a problem"),
    (r"Maximum of.*iterations exceeded in RedStp", "Maximum iterations exceeded in RedStp"),
    (r"Linear search skipped for unknown reason", "Linear search skipped for unknown reason"),
    (r"Inconsistency: ModMin=", "Inconsistency: ModMin"),
    (r"Variable has invalid number of steps", "Variable has invalid number of steps"),
    (r"Error in INITNF", "Error in INITNF"),
    (r"Delta-x Convergence NOT Met", "Delta-x Convergence NOT Met"),
    (r"GS2 Optimization Failure", "GS2 Optimization Failure"),
    (r"Problem with the distance matrix", "Problem with the distance matrix"),
    (r"Atom too close", "Atom too close"),
    (r"Change in point group or standard orientation", "Change in point group or standard orientation"),
    (r"FOPT requested but NVar=", "FOPT requested but NVar != NDOF"),
    (r"End of file reading basis center", "End of file reading basis center"),
    (r"EOF while reading ECP pointer card", "EOF while reading ECP pointer card"),
    (r"Atomic number out of range for basis set", "Atomic number out of range for basis set"),
    (r"No Q value available", "No Q value available"),
    (r"The combination of multiplicity and electrons is impossible", "The combination of multiplicity and electrons is impossible"),
    (r"Unable to choose the S8 parameter", "Unable to choose the S8 parameter"),
    (r"No RCov radius available", "No RCov radius available"),
    (r"No C6 coefficient available", "No C6 coefficient available"),
    (r"Unrecognized atomic symbol", "Unrecognized atomic symbol"),
    (r"Inconsistency #2 in MakNEB", "Inconsistency #2 in MakNEB"),
    (r"No .* atoms found in this molecule", "No X atoms found in this molecule"),
    (r"Unable to project read-in occupied orbitals", "Unable to project read-in occupied orbitals"),
    (r"MM microiterations failed", "MM microiterations failed"),
    (r"Convergence failure", "Convergence failure"),
    (r"Inaccurate quadrature in CalDSu", "Inaccurate quadrature in CalDSu"),
    (r"GetVDW: no radius for atom", "GetVDW: no radius for atom"),
    (r"Error on Z-matrix card", "Error on Z-matrix card"),
    (r"Excessive mixing of frozen core and valence orbitals", "Excessive mixing of frozen core and valence orbitals"),
    (r"Fatal Problem", "Fatal Problem"),
    (r"Consistency failure #1 in FindCO", "Consistency failure #1 in FindCO"),
    (r"KLT\.ge\.NIJTC in GetRSB", "KLT.ge.NIJTC in GetRSB"),
    (r"MAX\. CYCLES", "MAX. CYCLES"),
    (r"CISAX needs .* more words of memory", "CISAX needs more words of memory"),
    (r"No func 3rd derivs", "No func 3rd derivs"),
    (r"NIJ > Max2 in MMCore", "NIJ > Max2 in MMCore"),
    (r"words are not enough for AlAXAO", "Not enough words for AlAXAO"),
    (r"Wrong number of Negative eigenvalues", "Wrong number of Negative eigenvalues"),
    (r"Number of steps exceeded", "Number of steps exceeded"),
    (r"Determination of dummy atom variables in Z-matrix conversion failed", "Dummy atom variable determination failed"),
    (r"Erroneous write", "Erroneous write"),
    (r"malloc failed", "malloc failed"),
    (r"galloc: could not allocate memory", "galloc: could not allocate memory"),
    (r"No such file or directory", "No such file or directory"),
    (r"Files in the Gaussian directory are world accessible", "Files in the Gaussian directory are world accessible"),
    (r"Failed to open execfile", "Failed to open execfile"),
]

CORE_COLUMN_ALIASES: dict[str, list[str]] = {
    "name": ["name"],
    "structure": ["structure", "desc", "description"],
    "OPT_File": ["OPT_File", "OPT file", "opt_file", "opt path", "opt"],
    "Thermal correction to Enthalpy (TCE)": [
        "Thermal correction to Enthalpy (TCE)", "TCE", "thermal correction to enthalpy"
    ],
    "Thermal correction to Gibbs Free Energy (TCG)": [
        "Thermal correction to Gibbs Free Energy (TCG)", "TCG",
        "thermal correction to gibbs free energy", "gibbs correction"
    ],
    "single point energy (SPE)": [
        "single point energy (SPE)", "SPE", "single point energy", "sp energy"
    ],
    "enthalpies (H)": ["enthalpies (H)", "H", "enthalpy", "enthalpies"],
    "Gibbs free energies (G)": ["Gibbs free energies (G)", "G", "gibbs free energy", "gibbs"],
    "SP__File": ["SP__File", "SP_File", "SP file", "sp_file", "sp path", "sp"],
    "charge": ["charge"],
    "multiplicity": ["multiplicity", "mult"],
}

CANONICAL_HEADER_ORDER = [
    "name",
    "structure",
    "OPT_File",
    "Thermal correction to Enthalpy (TCE)",
    "Thermal correction to Gibbs Free Energy (TCG)",
    "single point energy (SPE)",
    "enthalpies (H)",
    "Gibbs free energies (G)",
    "SP__File",
    "charge",
    "multiplicity",
]


# ============================================================================
# UI helpers
# ============================================================================

def line(char: str = "=", width: int = 72) -> str:
    return char * width


def print_banner(current_dir: Path, extra: str | None = None) -> None:
    print("\n" + line("="))
    print("Enerdroid / Gaussian .out utility")
    print(f"版本 / Version: {VERSION}")
    print(line("="))
    print(f"当前目录 / Current directory: {current_dir}")
    if extra:
        print(extra)


def print_section(title_cn_en: str, char: str = "-") -> None:
    print("\n" + line(char))
    print(title_cn_en)
    print(line(char))


def print_summary_block(lines_: list[str]) -> None:
    print("\n" + line("="))
    for item in lines_:
        print(item)
    print(line("="))


def print_status(tag: str, message: str) -> None:
    print(f"[{tag}] {message}")


def print_progress(current: int, total: int, start_time: float, prefix: str = "") -> None:
    if total <= 0:
        return
    ratio = current / total
    bar_len = 30
    filled = int(bar_len * ratio)
    bar = "█" * filled + "-" * (bar_len - filled)
    elapsed = time.time() - start_time
    eta = (elapsed / current) * (total - current) if current > 0 else 0
    print(
        f"\r{prefix} [{bar}] {current}/{total} "
        f"({ratio*100:5.1f}%) | elapsed {elapsed:6.1f}s | ETA {eta:6.1f}s",
        end="",
        flush=True,
    )
    if current == total:
        print()


# ============================================================================
# Config helpers
# ============================================================================

def load_config(current_dir: Path) -> dict:
    config_path = current_dir / CONFIG_FILE_NAME
    if not config_path.exists():
        return {}
    try:
        with config_path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def save_config(current_dir: Path, config: dict) -> None:
    config_path = current_dir / CONFIG_FILE_NAME
    with config_path.open("w", encoding="utf-8") as f:
        json.dump(config, f, ensure_ascii=False, indent=2)


# ============================================================================
# General helpers
# ============================================================================

def read_text(file_path: Path) -> str:
    encodings = ["utf-8", "gb18030", "latin-1"]
    for enc in encodings:
        try:
            return file_path.read_text(encoding=enc, errors="replace")
        except Exception:
            continue
    raise RuntimeError(f"无法读取文件 / Cannot read file: {file_path}")


def normalize_header_name(text: str) -> str:
    return re.sub(r"\s+", " ", str(text).strip().lower())


def canonicalize_header(text: str) -> str | None:
    norm = normalize_header_name(text)
    for canonical, aliases in CORE_COLUMN_ALIASES.items():
        for alias in aliases:
            if norm == normalize_header_name(alias):
                return canonical
    return None


def try_float(value: Any) -> float | None:
    try:
        return float(value)
    except Exception:
        return None


def make_output_stem(input_stem: str, suffix: str) -> str:
    if input_stem.endswith("_BNY"):
        input_stem = input_stem[:-4] + "_bny"
    return f"{input_stem}{suffix}"


def get_gaussian_job_status(text: str) -> str:
    """
    Return:
    - SUCCESS
    - FAILED
    - UNFINISHED

    Rule:
    1. Find all termination-related events in the whole file.
    2. Use the LAST termination-related event as the final verdict.
    3. If the last one is 'Normal termination of Gaussian' -> SUCCESS
    4. If the last one is 'Error termination ...' -> FAILED
    5. If neither exists -> UNFINISHED
    """
    termination_events = []

    normal_pattern = re.compile(r"Normal termination of Gaussian", re.IGNORECASE)
    error_pattern = re.compile(r"Error termination", re.IGNORECASE)

    for m in normal_pattern.finditer(text):
        termination_events.append((m.start(), "SUCCESS"))

    for m in error_pattern.finditer(text):
        termination_events.append((m.start(), "FAILED"))

    if not termination_events:
        return "UNFINISHED"

    termination_events.sort(key=lambda x: x[0])
    return termination_events[-1][1]


def has_normal_termination(text: str) -> bool:
    return get_gaussian_job_status(text) == "SUCCESS"


def has_optimization_completed(text: str) -> bool:
    return "Optimization completed." in text


def extract_charge_and_multiplicity(text: str) -> tuple[int, int]:
    matches = re.findall(r"Charge\s*=\s*(-?\d+)\s+Multiplicity\s*=\s*(-?\d+)", text)
    if not matches:
        raise ValueError("未找到电荷和多重度信息 / Charge and multiplicity not found.")
    charge_str, mult_str = matches[-1]
    return int(charge_str), int(mult_str)


def extract_error_codes(text: str) -> list[str]:
    codes = []
    patterns = [
        r"Error termination via Lnk1e.*?[/\\](l\d+)\.exe",
        r"Error termination.*?[/\\](l\d+)\.exe",
        r"[/\\](l\d+)\.exe",
        r"\b(l\d+)\.exe\b",
    ]
    for pat in patterns:
        found = re.findall(pat, text, flags=re.IGNORECASE | re.DOTALL)
        for item in found:
            code = item.lower()
            if code not in codes:
                codes.append(code)
    return codes


def extract_common_error_messages(text: str) -> list[str]:
    found_messages = []
    for pattern, label in COMMON_ERROR_PATTERNS:
        if re.search(pattern, text, flags=re.IGNORECASE):
            if label not in found_messages:
                found_messages.append(label)
    return found_messages


def extract_last_float_after_label(text: str, label_pattern: str) -> float:
    matches = re.findall(label_pattern, text, flags=re.IGNORECASE)
    if not matches:
        raise ValueError(f"未找到目标字段 / Target field not found: {label_pattern}")
    return float(matches[-1])


def extract_tce(text: str) -> float:
    return extract_last_float_after_label(
        text,
        r"Thermal correction to Enthalpy=\s*([-+]?\d+\.\d+)"
    )


def extract_tcg(text: str) -> float:
    return extract_last_float_after_label(
        text,
        r"Thermal correction to Gibbs Free Energy=\s*([-+]?\d+\.\d+)"
    )


def extract_spe(text: str) -> float:
    matches = re.findall(
        r"SCF Done:\s+E\([^)]+\)\s*=\s*([-+]?\d+\.\d+)",
        text,
        flags=re.IGNORECASE
    )
    if not matches:
        raise ValueError("未找到单点能 / SCF Done energy not found.")
    return float(matches[-1])


def analyze_out_file(text: str) -> dict:
    status = get_gaussian_job_status(text)
    return {
        "job_status": status,  # SUCCESS / FAILED / UNFINISHED
        "normal_termination": status == "SUCCESS",
        "optimization_completed": has_optimization_completed(text),
        "error_codes": extract_error_codes(text),
        "error_messages": extract_common_error_messages(text),
    }


def family_key_from_name(name: str) -> str:
    if "_" in name:
        parts = name.split("_")
        if len(parts) >= 2:
            return "_".join(parts[:-1]).strip().lower()
    return name.strip().lower()


def name_similarity_anchor(name: str) -> str:
    return re.sub(r"(_v\d+)$", "", name.strip().lower())


# ============================================================================
# Coordinate parsing / gjf writing
# ============================================================================

def extract_last_orientation_block(text: str):
    lines = text.splitlines()
    standard_starts = []
    input_starts = []

    for i, line_ in enumerate(lines):
        if "Standard orientation:" in line_:
            standard_starts.append(i)
        elif "Input orientation:" in line_:
            input_starts.append(i)

    if standard_starts:
        block_start = standard_starts[-1]
    elif input_starts:
        block_start = input_starts[-1]
    else:
        raise ValueError("未找到最终坐标块 / No final orientation block found.")

    dash_indices = []
    for i in range(block_start, min(block_start + 20, len(lines))):
        if re.match(r"\s*-{5,}\s*$", lines[i]):
            dash_indices.append(i)

    if len(dash_indices) < 2:
        raise ValueError("坐标表格式异常 / Orientation block format error.")

    data_start = dash_indices[1] + 1
    coords = []

    for i in range(data_start, len(lines)):
        line_ = lines[i]
        if re.match(r"\s*-{5,}\s*$", line_):
            break

        parts = line_.split()
        if len(parts) < 6:
            continue

        try:
            atomic_number = int(parts[1])
            x = float(parts[3])
            y = float(parts[4])
            z = float(parts[5])
        except ValueError:
            continue

        symbol = ELEMENTS.get(atomic_number)
        if symbol is None:
            raise ValueError(f"未知原子序数 / Unknown atomic number: {atomic_number}")

        coords.append((symbol, x, y, z))

    if not coords:
        raise ValueError("未解析到坐标 / No coordinates parsed.")

    return coords


def write_gjf(output_path: Path, route_line: str, title: str, charge: int, multiplicity: int, coords) -> None:
    chk_name = output_path.with_suffix(".chk").name
    with output_path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(f"%chk={chk_name}\n")
        f.write(route_line.strip() + "\n\n")
        f.write(title + "\n\n")
        f.write(f"{charge} {multiplicity}\n")
        for symbol, x, y, z in coords:
            f.write(f"{symbol:<3s} {x:>16.8f} {y:>16.8f} {z:>16.8f}\n")
        f.write("\n")


# ============================================================================
# Convert mode
# ============================================================================

def get_route_line_interactively(current_dir: Path) -> str | None:
    config = load_config(current_dir)
    last_route = str(config.get("last_route_line", "")).strip()

    if last_route:
        print_section("转换设置 / Convert settings")
        print("检测到上一次的 route line / Last saved route line detected:")
        print(f"  {last_route}\n")
        answer = input("直接回车 = 使用上一次；输入 n = 输入新的\n> ").strip().lower()

        if answer == "":
            return last_route

        if answer == "n":
            new_route = input("\n请输入新的单点能 route line / Please enter a new route line:\n> ").strip()
            if not new_route:
                print_status("FAIL", "route line 不能为空 / route line cannot be empty.")
                return None
            config["last_route_line"] = new_route
            save_config(current_dir, config)
            return new_route

        print_status("FAIL", "输入无效 / Invalid input.")
        return None

    new_route = input("\n请输入单点能 route line / Please enter the single-point route line:\n> ").strip()
    if not new_route:
        print_status("FAIL", "route line 不能为空 / route line cannot be empty.")
        return None

    config["last_route_line"] = new_route
    save_config(current_dir, config)
    return new_route


def run_convert_mode(current_dir: Path) -> None:
    out_files = sorted(current_dir.glob("*.out"))

    print_banner(current_dir, extra=f"检测到 / Detected {len(out_files)} 个 .out 文件")
    print_section("转换模式 / Convert mode")

    if not out_files:
        print_status("FAIL", "当前文件夹没有 .out 文件 / No .out files found in current directory.")
        return

    route_line = get_route_line_interactively(current_dir)
    if not route_line:
        return

    suffix = input("\n请输入输出后缀（回车默认 _SP）/ Output suffix (Enter for _SP):\n> ").strip()
    if not suffix:
        suffix = "_SP"

    success_count = 0
    failed_count = 0
    skipped_count = 0

    start_time = time.time()
    total = len(out_files)

    for idx, out_file in enumerate(out_files, start=1):
        print_progress(idx - 1, total, start_time, prefix="转换进度 / Convert")

        try:
            output_stem = make_output_stem(out_file.stem, suffix)
            output_file = out_file.with_name(output_stem + ".gjf")

            if output_file.exists():
                print(f"\n[跳过 / SKIP] {out_file.name} -> {output_file.name} 已存在 / already exists.")
                skipped_count += 1
                continue

            text = read_text(out_file)

            if not has_optimization_completed(text):
                raise ValueError("未检测到 Optimization completed.")

            job_status = get_gaussian_job_status(text)
            if job_status != "SUCCESS":
                codes = extract_error_codes(text)
                messages = extract_common_error_messages(text)
                extra = [f"status={job_status}"]
                if codes:
                    extra.append("codes=" + ", ".join(codes))
                if messages:
                    extra.append("messages=" + "; ".join(messages))
                extra_text = f" ({' | '.join(extra)})" if extra else ""
                raise ValueError("Gaussian 未正常结束 / not normally terminated" + extra_text)

            charge, multiplicity = extract_charge_and_multiplicity(text)
            coords = extract_last_orientation_block(text)

            write_gjf(
                output_path=output_file,
                route_line=route_line,
                title=output_stem,
                charge=charge,
                multiplicity=multiplicity,
                coords=coords,
            )

            print(f"\n[成功 / OK] {out_file.name} -> {output_file.name} (charge={charge}, multiplicity={multiplicity})")
            success_count += 1

        except Exception as e:
            print(f"\n[失败 / FAIL] {out_file.name}: {e}")
            failed_count += 1

        print_progress(idx, total, start_time, prefix="转换进度 / Convert")

    print_summary_block([
        "转换完成 / Conversion finished",
        f"成功 / Success : {success_count}",
        f"跳过 / Skipped : {skipped_count}",
        f"失败 / Failed  : {failed_count}",
    ])


# ============================================================================
# Check mode
# ============================================================================

def run_check_termination_mode(current_dir: Path) -> None:
    out_files = sorted(current_dir.glob("*.out"))

    print_banner(current_dir, extra=f"检测到 / Detected {len(out_files)} 个 .out 文件")
    print_section("检测 .out 正常结束 / Check .out termination")

    if not out_files:
        print_status("FAIL", "当前文件夹没有 .out 文件 / No .out files found in current directory.")
        return

    normal_files = []
    abnormal_files = []

    start_time = time.time()
    total = len(out_files)

    for idx, out_file in enumerate(out_files, start=1):
        print_progress(idx - 1, total, start_time, prefix="检测进度 / Check")

        try:
            text = read_text(out_file)
            info = analyze_out_file(text)

            if info["job_status"] == "SUCCESS":
                normal_files.append(out_file.name)
            else:
                abnormal_files.append({
                    "file": out_file.name,
                    "job_status": info["job_status"],
                    "optimization_completed": info["optimization_completed"],
                    "error_codes": info["error_codes"],
                    "error_messages": info["error_messages"],
                })

        except Exception as e:
            abnormal_files.append({
                "file": out_file.name,
                "job_status": "UNFINISHED",
                "optimization_completed": False,
                "error_codes": [],
                "error_messages": [],
                "read_error": str(e),
            })

        print_progress(idx, total, start_time, prefix="检测进度 / Check")

    failed_count = sum(1 for x in abnormal_files if x.get("job_status") == "FAILED")
    unfinished_count = sum(1 for x in abnormal_files if x.get("job_status") == "UNFINISHED")

    print_summary_block([
        f"总 .out 文件数 / Total .out files           : {len(out_files)}",
        f"正常结束数 / Success count                 : {len(normal_files)}",
        f"报错终止数 / Failed count                  : {failed_count}",
        f"未跑完数 / Unfinished count                : {unfinished_count}",
    ])

    if not abnormal_files:
        print("全部正常结束 / All .out files terminated normally.")
        return

    print_section("异常文件列表 / Abnormal or unfinished files")

    status_map = {
        "FAILED": "报错终止 / Failed with error termination",
        "UNFINISHED": "未跑完 / Unfinished",
    }

    for item in abnormal_files:
        print(f"- {item['file']}")

        if "read_error" in item:
            print(f"    状态 / Status      : 读取失败 / Read error")
            print(f"    信息 / Message     : {item['read_error']}")
            continue

        job_status = item.get("job_status", "UNFINISHED")
        print(f"    状态 / Status      : {status_map.get(job_status, '未正常结束 / Not normally terminated')}")

        if item["optimization_completed"]:
            print("    优化状态 / Opt     : 已检测到 Optimization completed.")
        else:
            print("    优化状态 / Opt     : 未检测到 Optimization completed.")

        codes = item.get("error_codes", [])
        if codes:
            print(f"    错误代码 / Codes   : {', '.join(codes)}")
        else:
            print("    错误代码 / Codes   : 未识别 / Not detected")

        messages = item.get("error_messages", [])
        if messages:
            print("    错误信息 / Messages:")
            for msg in messages:
                print(f"      - {msg}")
        else:
            print("    错误信息 / Messages: 未匹配到常见错误信息 / No common error message matched")

    all_codes = []
    all_messages = []
    for item in abnormal_files:
        all_codes.extend(item.get("error_codes", []))
        all_messages.extend(item.get("error_messages", []))

    print_section("错误统计 / Error summary")
    print("错误代码统计 / Error code summary:")
    if all_codes:
        code_counter = Counter(all_codes)
        for code, count in sorted(code_counter.items()):
            print(f"  {code:<10s} : {count}")
    else:
        print("  未检测到 Gaussian link code / No Gaussian link code detected")

    print("\n常见错误信息统计 / Common error message summary:")
    if all_messages:
        msg_counter = Counter(all_messages)
        for msg, count in msg_counter.most_common():
            print(f"  {msg} : {count}")
    else:
        print("  未匹配到常见错误信息 / No common error message matched")


def run_check_missing_out_mode(current_dir: Path) -> None:
    gjf_files = sorted(current_dir.glob("*.gjf"))

    print_banner(current_dir, extra=f"检测到 / Detected {len(gjf_files)} 个 .gjf 文件")
    print_section("检测 .gjf 是否缺少对应 .out / Check .gjf without matching .out")

    if not gjf_files:
        print_status("FAIL", "当前文件夹没有 .gjf 文件 / No .gjf files found in current directory.")
        return

    matched = []
    unmatched = []

    start_time = time.time()
    total = len(gjf_files)

    for idx, gjf_file in enumerate(gjf_files, start=1):
        print_progress(idx - 1, total, start_time, prefix="检测进度 / Check")

        expected_out = current_dir / f"{gjf_file.stem}.out"
        if expected_out.exists():
            matched.append(gjf_file.name)
        else:
            unmatched.append(gjf_file.name)

        print_progress(idx, total, start_time, prefix="检测进度 / Check")

    print_summary_block([
        f"总 .gjf 文件数 / Total .gjf files        : {len(gjf_files)}",
        f"有对应 .out 的数 / With matching .out    : {len(matched)}",
        f"无对应 .out 的数 / Without matching .out : {len(unmatched)}",
    ])

    if unmatched:
        print("没有对应 .out 的 .gjf 文件 / .gjf files without matching .out:")
        for name in unmatched:
            print(f"  - {name}")
    else:
        print("全部 .gjf 都有对应的 .out / All .gjf files have matching .out files.")


def run_check_mode(current_dir: Path) -> None:
    while True:
        print_banner(current_dir)
        print_section("检测子功能 / Check sub-functions")

        print("  1 - 检测 .out 是否正常结束 / Check .out termination status")
        print("  2 - 检测有没有 .gjf 没有对应的 .out / Check .gjf without matching .out")
        print("  3 - 返回主菜单 / Return to main menu")

        sub_choice = input("\n请输入 1 / 2 / 3:\n> ").strip()

        if sub_choice == "1":
            run_check_termination_mode(current_dir)
        elif sub_choice == "2":
            run_check_missing_out_mode(current_dir)
        elif sub_choice == "3":
            break
        else:
            print_status("FAIL", "输入无效 / Invalid selection.")


# ============================================================================
# Statistics mode
# ============================================================================

def find_latest_energy_excel(current_dir: Path) -> Path | None:
    folder_name = current_dir.name
    pattern = re.compile(rf"^{re.escape(folder_name)}_Energy_(\d{{6}})\.xlsx$", re.IGNORECASE)

    matched = []
    for f in current_dir.glob("*.xlsx"):
        m = pattern.match(f.name)
        if m:
            matched.append((m.group(1), f))

    if not matched:
        return None

    matched.sort(key=lambda x: x[0], reverse=True)
    return matched[0][1]


def get_today_energy_excel_name(current_dir: Path) -> str:
    folder_name = current_dir.name
    date_str = datetime.now().strftime("%y%m%d")
    return f"{folder_name}_Energy_{date_str}.xlsx"


def collect_statistics_pairs(current_dir: Path) -> tuple[list[dict], list[str]]:
    opt_files = sorted(current_dir.glob("*.out"))
    records = []
    skipped_messages = []

    total = len(opt_files)
    start_time = time.time()

    for idx, opt_file in enumerate(opt_files, start=1):
        print_progress(idx - 1, total, start_time, prefix="统计扫描 / Stats")

        stem = opt_file.stem
        if stem.endswith("_SP"):
            print_progress(idx, total, start_time, prefix="统计扫描 / Stats")
            continue

        expected_sp_stem = make_output_stem(stem, "_SP")
        sp_file = current_dir / f"{expected_sp_stem}.out"

        if not sp_file.exists():
            skipped_messages.append(f"[跳过] {opt_file.name} 缺少配对单点文件 {sp_file.name}")
            print_progress(idx, total, start_time, prefix="统计扫描 / Stats")
            continue

        try:
            opt_text = read_text(opt_file)
            sp_text = read_text(sp_file)

            opt_status = get_gaussian_job_status(opt_text)
            sp_status = get_gaussian_job_status(sp_text)

            if opt_status != "SUCCESS":
                skipped_messages.append(f"[跳过] {opt_file.name} 未成功完成（status={opt_status}）")
                print_progress(idx, total, start_time, prefix="统计扫描 / Stats")
                continue

            if sp_status != "SUCCESS":
                skipped_messages.append(f"[跳过] {sp_file.name} 未成功完成（status={sp_status}）")
                print_progress(idx, total, start_time, prefix="统计扫描 / Stats")
                continue

            opt_charge, opt_mult = extract_charge_and_multiplicity(opt_text)
            sp_charge, sp_mult = extract_charge_and_multiplicity(sp_text)

            tce = extract_tce(opt_text)
            tcg = extract_tcg(opt_text)
            spe = extract_spe(sp_text)
            h_value = tce + spe
            g_value = tcg + spe

            charge_value: Any = opt_charge if opt_charge == sp_charge else f"mismatch: OPT={opt_charge}, SP={sp_charge}"
            mult_value: Any = opt_mult if opt_mult == sp_mult else f"mismatch: OPT={opt_mult}, SP={sp_mult}"

            records.append({
                "key": stem,
                "name": stem,
                "family_key": family_key_from_name(stem),
                "family_anchor": name_similarity_anchor(stem),
                "structure": "",
                "OPT_File": str(opt_file.resolve()),
                "Thermal correction to Enthalpy (TCE)": tce,
                "Thermal correction to Gibbs Free Energy (TCG)": tcg,
                "single point energy (SPE)": spe,
                "enthalpies (H)": h_value,
                "Gibbs free energies (G)": g_value,
                "SP__File": str(sp_file.resolve()),
                "charge": charge_value,
                "multiplicity": mult_value,
            })

        except Exception as e:
            skipped_messages.append(f"[跳过] {opt_file.name} / {sp_file.name} 统计失败: {e}")

        print_progress(idx, total, start_time, prefix="统计扫描 / Stats")

    return records, skipped_messages


def style_new_statistics_sheet(ws) -> None:
    header_fill = PatternFill("solid", fgColor="1F4E78")
    header_font = Font(color="FFFFFF", bold=True)
    thin_gray = Side(style="thin", color="D9D9D9")
    header_border = Border(bottom=thin_gray)

    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.border = header_border
        cell.alignment = Alignment(horizontal="center", vertical="center")

    widths = {
        "A": 20, "B": 20, "C": 55, "D": 18, "E": 18, "F": 18,
        "G": 18, "H": 18, "I": 55, "J": 24, "K": 24,
    }
    for col, width in widths.items():
        ws.column_dimensions[col].width = width

    ws.freeze_panes = "A2"
    ws.row_dimensions[1].height = 22

    for row in range(2, ws.max_row + 1):
        for col in ["D", "E", "F", "G", "H"]:
            ws[f"{col}{row}"].number_format = "0.0000000000"


def create_new_statistics_workbook(excel_path: Path, records: list[dict]) -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Energy"

    for col_idx, header in enumerate(CANONICAL_HEADER_ORDER, start=1):
        ws.cell(row=1, column=col_idx).value = header

    for row_idx, rec in enumerate(records, start=2):
        ws.cell(row=row_idx, column=1).value = rec["name"]
        ws.cell(row=row_idx, column=2).value = rec["structure"]
        ws.cell(row=row_idx, column=3).value = rec["OPT_File"]
        ws.cell(row=row_idx, column=4).value = rec["Thermal correction to Enthalpy (TCE)"]
        ws.cell(row=row_idx, column=5).value = rec["Thermal correction to Gibbs Free Energy (TCG)"]
        ws.cell(row=row_idx, column=6).value = rec["single point energy (SPE)"]
        ws.cell(row=row_idx, column=7).value = f"=D{row_idx}+F{row_idx}"
        ws.cell(row=row_idx, column=8).value = f"=E{row_idx}+F{row_idx}"
        ws.cell(row=row_idx, column=9).value = rec["SP__File"]
        ws.cell(row=row_idx, column=10).value = rec["charge"]
        ws.cell(row=row_idx, column=11).value = rec["multiplicity"]

    style_new_statistics_sheet(ws)
    wb.save(excel_path)


def build_header_maps(ws) -> tuple[dict[str, int], dict[int, str]]:
    canonical_to_col = {}
    col_to_canonical = {}

    for col in range(1, ws.max_column + 1):
        value = ws.cell(row=1, column=col).value
        if value is None:
            continue
        canonical = canonicalize_header(str(value))
        if canonical and canonical not in canonical_to_col:
            canonical_to_col[canonical] = col
            col_to_canonical[col] = canonical

    return canonical_to_col, col_to_canonical


def ensure_core_columns(ws) -> dict[str, int]:
    canonical_to_col, _ = build_header_maps(ws)

    if "name" not in canonical_to_col:
        ws.insert_cols(1, amount=1)
        ws.cell(row=1, column=1).value = "name"

    canonical_to_col, _ = build_header_maps(ws)

    if "structure" not in canonical_to_col:
        ws.insert_cols(2, amount=1)
        ws.cell(row=1, column=2).value = "structure"

    canonical_to_col, _ = build_header_maps(ws)

    for canonical in CANONICAL_HEADER_ORDER:
        if canonical not in canonical_to_col:
            col = ws.max_column + 1
            ws.cell(row=1, column=col).value = canonical

    canonical_to_col, _ = build_header_maps(ws)
    return canonical_to_col


def detect_row_key(row_values_by_canonical: dict[str, Any]) -> str | None:
    name_val = row_values_by_canonical.get("name")
    if name_val:
        return str(name_val).strip()

    opt_val = row_values_by_canonical.get("OPT_File")
    if opt_val:
        try:
            return Path(str(opt_val)).stem
        except Exception:
            return None

    return None


def read_existing_rows(ws, canonical_to_col: dict[str, int]) -> tuple[list[dict], dict[str, dict]]:
    all_rows = []
    keyed_rows_map = {}

    for row in range(2, ws.max_row + 1):
        row_cells = [ws.cell(row=row, column=col) for col in range(1, ws.max_column + 1)]
        values = [cell.value for cell in row_cells]

        styles = []
        for cell in row_cells:
            styles.append({
                "font": copy.copy(cell.font),
                "fill": copy.copy(cell.fill),
                "border": copy.copy(cell.border),
                "alignment": copy.copy(cell.alignment),
                "number_format": cell.number_format,
                "protection": copy.copy(cell.protection),
                "hyperlink": copy.copy(cell.hyperlink),
            })

        canonical_values = {}
        for canonical, col in canonical_to_col.items():
            canonical_values[canonical] = ws.cell(row=row, column=col).value

        row_data = {
            "row_index": row,
            "values": values,
            "styles": styles,
            "canonical_values": canonical_values,
        }
        all_rows.append(row_data)

        key = detect_row_key(canonical_values)
        if key:
            keyed_rows_map[key] = row_data

    return all_rows, keyed_rows_map


def compare_core_data(old_canonical_values: dict[str, Any], new_record: dict) -> list[str]:
    changes = []
    fields = [
        "name",
        "OPT_File",
        "Thermal correction to Enthalpy (TCE)",
        "Thermal correction to Gibbs Free Energy (TCG)",
        "single point energy (SPE)",
        "SP__File",
        "charge",
        "multiplicity",
    ]

    for field in fields:
        old_val = old_canonical_values.get(field)
        new_val = new_record.get(field)
        old_num = try_float(old_val)
        new_num = try_float(new_val)

        if old_num is not None and new_num is not None:
            if abs(old_num - new_num) > 1e-10:
                changes.append(f"{field}: {old_val} -> {new_val}")
        else:
            if str(old_val) != str(new_val):
                changes.append(f"{field}: {old_val} -> {new_val}")

    return changes


def make_blank_row_template(ws) -> dict:
    values = [None] * ws.max_column
    styles = []
    template_source_row = 2 if ws.max_row >= 2 else 1

    for col in range(1, ws.max_column + 1):
        cell = ws.cell(row=template_source_row, column=col)
        styles.append({
            "font": copy.copy(cell.font),
            "fill": copy.copy(cell.fill),
            "border": copy.copy(cell.border),
            "alignment": copy.copy(cell.alignment),
            "number_format": cell.number_format,
            "protection": copy.copy(cell.protection),
            "hyperlink": copy.copy(cell.hyperlink),
        })

    return {
        "row_index": None,
        "values": values,
        "styles": styles,
        "canonical_values": {},
    }


def update_or_create_row_data(
    old_row_data: dict | None,
    template_row_data: dict,
    new_record: dict,
    canonical_to_col: dict[str, int]
) -> dict:
    row_data = copy.deepcopy(old_row_data if old_row_data is not None else template_row_data)

    old_structure = None
    if old_row_data is not None:
        old_structure = old_row_data["canonical_values"].get("structure")

    row_data["canonical_values"]["name"] = new_record["name"]
    row_data["canonical_values"]["structure"] = old_structure if old_structure is not None else new_record.get("structure", "")
    row_data["canonical_values"]["OPT_File"] = new_record["OPT_File"]
    row_data["canonical_values"]["Thermal correction to Enthalpy (TCE)"] = new_record["Thermal correction to Enthalpy (TCE)"]
    row_data["canonical_values"]["Thermal correction to Gibbs Free Energy (TCG)"] = new_record["Thermal correction to Gibbs Free Energy (TCG)"]
    row_data["canonical_values"]["single point energy (SPE)"] = new_record["single point energy (SPE)"]
    row_data["canonical_values"]["SP__File"] = new_record["SP__File"]
    row_data["canonical_values"]["charge"] = new_record["charge"]
    row_data["canonical_values"]["multiplicity"] = new_record["multiplicity"]
    row_data["canonical_values"]["enthalpies (H)"] = new_record["enthalpies (H)"]
    row_data["canonical_values"]["Gibbs free energies (G)"] = new_record["Gibbs free energies (G)"]

    for canonical, col in canonical_to_col.items():
        idx = col - 1
        if canonical in row_data["canonical_values"]:
            row_data["values"][idx] = row_data["canonical_values"][canonical]

    return row_data


def sort_statistics_records(records: list[dict]) -> list[dict]:
    """
    Sorting strategy:
    1. Build family groups by file-name relatedness.
    2. Across groups: sort by the minimum G in each group.
    3. Inside a group: keep the family anchor near its closest-energy relatives.
       This favors items like xxy and xxy_V2 when both name and energy are close.
    """
    families: dict[str, list[dict]] = {}
    for rec in records:
        families.setdefault(rec["family_key"], []).append(rec)

    family_blocks = []

    for family_key, members in families.items():
        members = sorted(members, key=lambda x: (x["Gibbs free energies (G)"], x["name"].lower()))
        anchor = members[0]
        anchor_name = anchor["family_anchor"]
        anchor_g = anchor["Gibbs free energies (G)"]

        def member_key(rec: dict):
            name_penalty = 0 if rec["family_anchor"] == anchor_name else 1
            energy_penalty = abs(rec["Gibbs free energies (G)"] - anchor_g)
            length_penalty = abs(len(rec["name"]) - len(anchor["name"]))
            return (name_penalty, energy_penalty, length_penalty, rec["Gibbs free energies (G)"], rec["name"].lower())

        ordered = sorted(members, key=member_key)
        family_min_g = min(x["Gibbs free energies (G)"] for x in members)
        family_blocks.append((family_min_g, family_key, ordered))

    family_blocks.sort(key=lambda x: (x[0], x[1]))

    final_records = []
    for _, _, ordered in family_blocks:
        final_records.extend(ordered)

    return final_records


def write_row_data_back_to_sheet(ws, row_idx: int, row_data: dict, canonical_to_col: dict[str, int]) -> None:
    for col_idx, value in enumerate(row_data["values"], start=1):
        cell = ws.cell(row=row_idx, column=col_idx)
        cell.value = value

        style_data = row_data["styles"][col_idx - 1]
        cell.font = copy.copy(style_data["font"])
        cell.fill = copy.copy(style_data["fill"])
        cell.border = copy.copy(style_data["border"])
        cell.alignment = copy.copy(style_data["alignment"])
        cell.number_format = style_data["number_format"]
        cell.protection = copy.copy(style_data["protection"])
        cell.hyperlink = copy.copy(style_data["hyperlink"])

    for canonical, col in canonical_to_col.items():
        cell = ws.cell(row=row_idx, column=col)

        if canonical == "enthalpies (H)":
            tce_col = canonical_to_col["Thermal correction to Enthalpy (TCE)"]
            spe_col = canonical_to_col["single point energy (SPE)"]
            cell.value = f"={get_column_letter(tce_col)}{row_idx}+{get_column_letter(spe_col)}{row_idx}"
            cell.number_format = "0.0000000000"
            continue

        if canonical == "Gibbs free energies (G)":
            tcg_col = canonical_to_col["Thermal correction to Gibbs Free Energy (TCG)"]
            spe_col = canonical_to_col["single point energy (SPE)"]
            cell.value = f"={get_column_letter(tcg_col)}{row_idx}+{get_column_letter(spe_col)}{row_idx}"
            cell.number_format = "0.0000000000"
            continue

        if canonical in row_data["canonical_values"]:
            cell.value = row_data["canonical_values"][canonical]
            if canonical in {
                "Thermal correction to Enthalpy (TCE)",
                "Thermal correction to Gibbs Free Energy (TCG)",
                "single point energy (SPE)",
            }:
                cell.number_format = "0.0000000000"


def remove_extra_data_rows(ws, start_row: int) -> None:
    if ws.max_row >= start_row:
        ws.delete_rows(start_row, ws.max_row - start_row + 1)


def run_statistics_mode(current_dir: Path) -> None:
    print_banner(current_dir)
    print_section("统计模式 / Statistics mode")

    latest_excel = find_latest_energy_excel(current_dir)
    today_excel_name = get_today_energy_excel_name(current_dir)
    today_excel_path = current_dir / today_excel_name

    records, skipped_messages = collect_statistics_pairs(current_dir)
    records = sort_statistics_records(records)

    temp_output = current_dir / (today_excel_name + ".tmp.xlsx")

    if latest_excel is None:
        print("未检测到已有汇总表 / No existing Excel detected. A new one will be created.")
        for rec in records:
            rec["structure"] = ""
        create_new_statistics_workbook(temp_output, records)
        change_messages = [f"[新增 / NEW] {rec['name']}" for rec in records]

    else:
        print(f"检测到已有汇总表 / Existing Excel detected: {latest_excel.name}")

        wb = load_workbook(latest_excel)
        ws = wb.active

        canonical_to_col = ensure_core_columns(ws)
        _, keyed_rows_map = read_existing_rows(ws, canonical_to_col)

        change_messages = []
        template_row = make_blank_row_template(ws)
        new_row_data_list = []

        for rec in records:
            key = rec["key"]
            old_row_data = keyed_rows_map.get(key)

            if old_row_data is None:
                change_messages.append(f"[新增 / NEW] {rec['name']}")
            else:
                changes = compare_core_data(old_row_data["canonical_values"], rec)
                if changes:
                    change_messages.append(f"[更新 / UPDATE] {rec['name']}: " + " | ".join(changes))

            new_row_data = update_or_create_row_data(
                old_row_data=old_row_data,
                template_row_data=template_row,
                new_record=rec,
                canonical_to_col=canonical_to_col,
            )
            new_row_data_list.append(new_row_data)

        old_keys = set(keyed_rows_map.keys())
        new_keys = {rec["key"] for rec in records}
        for key in sorted(old_keys - new_keys):
            change_messages.append(f"[移除 / REMOVE] {key}（旧表中有，但本次扫描未纳入统计）")

        remove_extra_data_rows(ws, 2)

        for idx, row_data in enumerate(new_row_data_list, start=2):
            ws.insert_rows(idx)
            write_row_data_back_to_sheet(ws, idx, row_data, canonical_to_col)

        wb.save(temp_output)

    if latest_excel is not None:
        if today_excel_path.exists() and today_excel_path != latest_excel:
            today_excel_path.unlink()
        if latest_excel.exists() and latest_excel != today_excel_path:
            try:
                latest_excel.unlink()
            except Exception:
                pass

    if today_excel_path.exists():
        today_excel_path.unlink()

    temp_output.rename(today_excel_path)

    print_summary_block([
        "统计完成 / Statistics finished",
        f"输出表格 / Output Excel: {today_excel_path.name}",
        f"纳入统计的配对数 / Included pairs: {len(records)}",
        f"跳过的文件/配对数 / Skipped items: {len(skipped_messages)}",
    ])

    if skipped_messages:
        print_section("跳过详情 / Skipped details")
        for msg in skipped_messages:
            print(" ", msg)

    if change_messages:
        print_section("变更详情 / Changes detected")
        for msg in change_messages:
            print(" ", msg)
    else:
        print("\n未检测到数据变化 / No data changes detected.")

    print_section("说明 / Notes")
    print("  - name 列已加入 / name column added")
    print("  - structure 列保留旧描述 / structure column preserved")
    print("  - 其余核心列已刷新 / other core columns refreshed")
    print("  - 核心列支持别名识别 / core column aliases supported")
    print("  - 仅纳入 SUCCESS 文件对 / only SUCCESS pairs are included")
    print("  - 排序更强调‘名字相近 + 能量接近’ / sorting emphasizes both name and energy proximity")
    print("  - H 列公式 = TCE + SPE")
    print("  - G 列公式 = TCG + SPE")


# ============================================================================
# Exit handling
# ============================================================================

def handle_exit(current_dir: Path) -> None:
    config = load_config(current_dir)
    custom_exit = str(config.get("custom_exit_message", "")).strip()

    print_section("退出设置 / Exit settings")
    if custom_exit:
        print(f"当前自定义结束语 / Current custom exit line:\n  {custom_exit}")
    else:
        print("当前自定义结束语 / Current custom exit line:\n  (无 / none)")

    new_line = input(
        "\n输入新的结束语 = 覆盖；直接回车 = 保持；输入 clear = 清空\n> "
    ).strip()

    if new_line.lower() == "clear":
        config["custom_exit_message"] = ""
        save_config(current_dir, config)
        custom_exit = ""
        print_status("OK", "自定义结束语已清空 / Custom exit line cleared.")
    elif new_line:
        config["custom_exit_message"] = new_line
        save_config(current_dir, config)
        custom_exit = new_line
        print_status("OK", "自定义结束语已更新 / Custom exit line updated.")

    print("\n" + FIXED_EXIT_SLOGAN)
    if custom_exit:
        print(custom_exit)


# ============================================================================
# Main menu
# ============================================================================

def print_main_menu(current_dir: Path) -> None:
    config = load_config(current_dir)
    custom_exit = str(config.get("custom_exit_message", "")).strip()
    last_route = str(config.get("last_route_line", "")).strip()

    extras = [
        f"检测到 / Detected {len(list(current_dir.glob('*.out')))} 个 .out 文件",
        f"检测到 / Detected {len(list(current_dir.glob('*.gjf')))} 个 .gjf 文件",
    ]
    if last_route:
        extras.append(f"上次 route line / Last route line: {last_route}")
    if custom_exit:
        extras.append(f"自定义结束语 / Custom exit line: {custom_exit}")

    print_banner(current_dir, extra="\n".join(extras))
    print_section("主菜单 / Main menu")
    print("  1 - 转换模式 / Convert .out to single-point .gjf")
    print("  2 - 检测模式 / Check mode")
    print("  3 - 统计模式 / Build or update Energy Excel")
    print("  4 - 退出 / Exit")


def main() -> None:
    current_dir = Path.cwd()

    while True:
        print_main_menu(current_dir)
        choice = input("\n请输入 1 / 2 / 3 / 4:\n> ").strip()

        if choice == "1":
            run_convert_mode(current_dir)
        elif choice == "2":
            run_check_mode(current_dir)
        elif choice == "3":
            run_statistics_mode(current_dir)
        elif choice == "4":
            handle_exit(current_dir)
            break
        else:
            print_status("FAIL", "输入无效 / Invalid selection.")


if __name__ == "__main__":
    try:
        main()
    except ModuleNotFoundError as e:
        if "openpyxl" in str(e):
            print("缺少 openpyxl 模块。请先安装：")
            print("python -m pip install openpyxl")
        else:
            raise